# Generated by Django 5.2 on 2025-04-27 14:02

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptDomain',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='도메인 코드')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='도메인 명칭')),
                ('description', models.TextField(blank=True, help_text='도메인에 대한 상세 설명', verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='concept.conceptdomain', verbose_name='상위 도메인')),
            ],
            options={
                'verbose_name': '개념 도메인',
                'verbose_name_plural': '개념 도메인',
                'db_table': 'concept_domains',
                'ordering': ['name'],
            },
        ),
    ]
