# Generated by Django 5.2 on 2025-04-27 14:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='개념명')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='슬러그')),
                ('confidence', models.FloatField(default=0.0, help_text='0.0~1.0 사이의 값', verbose_name='신뢰도')),
                ('vector_embedding', models.JSONField(blank=True, help_text='개념의 의미적 임베딩 벡터', null=True, verbose_name='벡터 임베딩')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='검토 여부')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='content.content', verbose_name='출처 콘텐츠')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts', to='concept.conceptdomain', verbose_name='도메인')),
            ],
            options={
                'verbose_name': '개념',
                'verbose_name_plural': '개념',
                'db_table': 'concepts',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='ConceptCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='concept.conceptdomain')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptClusterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('relevance_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='concept.conceptcluster')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='concept.concept')),
            ],
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['name'], name='concepts_name_862751_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['confidence'], name='concepts_confide_dc2256_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptcluster',
            unique_together={('name', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='conceptclustermembership',
            unique_together={('concept', 'cluster')},
        ),
    ]
