# Generated by Django 5.2 on 2025-04-30 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concept', '0001_initial'),
        ('entity', '0001_initial'),
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', '처리 대기'), ('processing', '처리 중'), ('completed', '처리 완료'), ('failed', '처리 실패')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(related_name='articles', to='concept.conceptdomain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '기사',
                'verbose_name_plural': '기사 목록',
            },
        ),
        migrations.CreateModel(
            name='ArticleConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('is_key_concept', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concept.concept')),
            ],
            options={
                'unique_together': {('article', 'concept')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='concepts',
            field=models.ManyToManyField(related_name='articles', through='article.ArticleConcept', to='concept.concept'),
        ),
        migrations.CreateModel(
            name='ArticleEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('mention_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'unique_together': {('article', 'entity')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='entities',
            field=models.ManyToManyField(related_name='articles', through='article.ArticleEntity', to='entity.entity'),
        ),
        migrations.CreateModel(
            name='ArticleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(default='PART_OF', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'unique_together': {('article', 'event')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='events',
            field=models.ManyToManyField(related_name='articles', through='article.ArticleEvent', to='event.event'),
        ),
        migrations.CreateModel(
            name='ArticleRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=50)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='article.article')),
                ('target_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationships', to='article.article')),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['user', '-created_at'], name='article_art_user_id_68fba4_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['processing_status'], name='article_art_process_3e1951_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articlerelationship',
            unique_together={('source_article', 'target_article', 'relationship_type')},
        ),
    ]
