# Generated by Django 5.2 on 2025-04-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_type', models.CharField(default='web', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('emotional_tone', models.CharField(db_index=True, max_length=50)),
                ('temporal_context', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_analysis', models.JSONField(blank=True, null=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='knowledgesnode.content')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('confidence', models.FloatField()),
                ('vector_embedding', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='knowledgesnode.contentanalysis')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'confidence'], name='knowledgesn_name_88a68a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoreTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(db_index=True, max_length=200)),
                ('content_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_themes', to='knowledgesnode.contentanalysis')),
            ],
            options={
                'unique_together': {('content_analysis', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='KeyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField()),
                ('content_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_claims', to='knowledgesnode.contentanalysis')),
            ],
            options={
                'unique_together': {('content_analysis', 'claim')},
            },
        ),
        migrations.CreateModel(
            name='KeyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=100)),
                ('content_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_terms', to='knowledgesnode.contentanalysis')),
            ],
            options={
                'unique_together': {('content_analysis', 'term')},
            },
        ),
        migrations.CreateModel(
            name='RelatedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=100)),
                ('content_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_domains', to='knowledgesnode.contentanalysis')),
            ],
            options={
                'unique_together': {('content_analysis', 'domain')},
            },
        ),
    ]
