# Generated by Django 5.2 on 2025-04-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledgesnode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='knowledgesnode.concept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='knowledgesnode.concept')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'strength'], name='connection__source__0c8ba1_idx'), models.Index(fields=['target', 'strength'], name='connection__target__3500e5_idx')],
            },
        ),
    ]
