# Generated by Django 5.2 on 2025-04-27 14:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concept', '0002_concept_conceptcluster_conceptclustermembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strength', models.FloatField(default=0.0, help_text='0.0~1.0 사이의 값으로 연결 강도 표현', verbose_name='연결 강도')),
                ('relation_type', models.CharField(blank=True, help_text='is_a, part_of, related_to 등', max_length=50, verbose_name='관계 유형')),
                ('is_manual', models.BooleanField(default=False, help_text='사용자가 직접 추가한 연결인지 여부', verbose_name='수동 생성 여부')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='concept.concept', verbose_name='출발 개념')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='concept.concept', verbose_name='도착 개념')),
            ],
            options={
                'verbose_name': '개념 연결',
                'verbose_name_plural': '개념 연결',
                'db_table': 'connections',
                'ordering': ['-strength'],
                'indexes': [models.Index(fields=['source', 'target'], name='connections_source__f105bd_idx'), models.Index(fields=['strength'], name='connections_strengt_f362ab_idx')],
            },
        ),
    ]
