# Generated by Django 5.2 on 2025-04-27 14:02

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=600, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='출처 URL')),
                ('source_type', models.CharField(default='web', help_text='web, pdf, image, audio 등', max_length=50, verbose_name='소스 타입')),
                ('is_processed', models.BooleanField(default=False, verbose_name='처리 완료 여부')),
                ('primary_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contents', to='concept.conceptdomain', verbose_name='주요 도메인')),
            ],
            options={
                'verbose_name': '컨텐츠',
                'verbose_name_plural': '컨텐츠',
                'db_table': 'contents',
                'ordering': ['-created'],
            },
        ),
    ]
